version = 1
SPDX-PackageName = "CiteScoop"
SPDX-PackageSupplier = "The University of St Andrews"
[[annotations]]
path = ["test/src/**/data/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 The University of St Andrews"
SPDX-License-Identifier = "GPL-3.0-or-later"
